version: "3.2"

volumes:
  suricata:
  
services:
  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    hostname: logstash
    container_name: logstash
    restart: always
    ports:
      - 5044:5044
    volumes:
      - ./json-data/eve.json:/usr/share/logstash/logs/eve.json
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    environment:
      LOG_LEVEL: error

  suricata:
    build: ./suricata
    container_name: suricata
    image: suricata
    restart: always
    environment:
      - OINKCODE=OPEN
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./json-data/eve.json:/var/log/suricata/eve.json
      - ./suricata/rules/my.rules:/var/lib/suricata/rules/my.rules
      - ./suricata/docker-entrypoint.sh:/tmp/docker-entrypoint.sh
      - ./suricata/suricata-update-cron:/etc/crontabs/suricata-update-cron
      - ./suricata/suricata-update.sh:/tmp/suricata-update.sh
      - ./suricata/scripts/get_signature_ids.sh:/tmp/get_signature_ids.sh
      - ./suricata/suricata.yaml:/etc/suricata/suricata.yaml
    command: sh -c "sh /tmp/docker-entrypoint.sh"

  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_INITDB_COLLECTION: "${MONGO_INITDB_COLLECTION}"
      MONGO_INITDB_DATABASE: "${MONGO_INITDB_DATABASE}"      
      PUID: 1000
      PGID: 1000
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/database:/data/db
      - ./mongodb/entrypoint/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js